### ISSUE TITLE
Badge for js-green-licenses

### ISSUE THREAD

**Issue by jinwoo** [google/js-green-licenses#11]
Would be good to add a badge that can be used in README files.

**Comment by ofrobots** [comment]
How about https://img.shields.io/badge/licences-green-green.svg: ![badge](https://img.shields.io/badge/licences-green-green.svg)

**Comment by jinwoo** [comment]
Looks great!

**Comment by ofrobots** [comment]
Not clear if there is an easy way to do this without having a server.
