### ISSUE TITLE
"UNLICENSED" should not be corrected to "Unlicense"

### ISSUE THREAD

**Issue by zypA13510** [google/js-green-licenses#113]
```
Correcting UNLICENSED to Unlicense
```

This is very wrong, it is exactly the opposite of what "UNLICENSED" means.
This is caused by calling `spdxCorrect()` directly without checking for "UNLICENSED" first: [checker.ts:198](https://github.com/google/js-green-licenses/blob/52bd1c659efccc28d4009f168664ba29f23b9da1/src/checker.ts#L198)
It is a known issue of `spdx-correct` but the author decided not to fix: jslicense/spdx-correct.js#3

**Comment by mat-sz** [comment]
I've created a PR to fix this issue: #134.
