### ISSUE TITLE
js-green-licenses outputs (no license) for node-only package

### ISSUE THREAD

**Issue by smashercosmo** [google/js-green-licenses#116]
When I run js-green-licenses for my project I get 
```
(no license): only@0.0.2
  my-project-name@1.0.0 -> koa@2.11.0 -> only@0.0.2
```
Though this package has all the essential license data:
https://github.com/tj/node-only/blob/master/package.json#L7
https://github.com/tj/node-only/blob/master/LICENSE

**Comment by jinwoo** [comment]
The addition of the license on GitHub was never published. See
- https://www.npmjs.com/package/only
- https://github.com/tj/node-only/commit/9879ee5e43feb9433cd69290b760d212a7ba8cd2

**Comment by smashercosmo** [comment]
thx
