### ISSUE TITLE
Broken subpackages can't be whitelisted

### ISSUE THREAD

**Issue by pdemarino** [google/js-green-licenses#118]
I am trying to automate license verification for a package, and a transitive dependency is `eyes@1.8.x`, which has a broken `package.json`.

Can such a package be whitelisted?

Steps to replicate:

```
npm init
npm i winston@2.4.4
npx js-green-licenses --local .
```

**Comment by bcoe** [comment]
:wave: sounds like it would be us worth handling this edge-case, thanks for reporting.

**Comment by pdemarino** [comment]
Thank you - this library has made my life so much easier!
