### ISSUE TITLE
bug: Package name mismatch. Expected undefined, but got undefined

### ISSUE THREAD

**Issue by acao** [google/js-green-licenses#160]
First off, this project is awesome, thank you! thinking it can save the GraphQL and Linux foundation some time.

This bug occurs for just a few packages, but the rest seem to be fine? I looked at other bugs here and I don't think this is a duplicate? This it the first time we've had a bug with this library.

https://github.com/graphql/graphiql/runs/2261177973?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1368727/113517120-3558d780-954c-11eb-849d-dd6a1b5f3682.png)

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the kind words!  Which specific issue is giving you trouble?  Is it the `Package name mismatch` warning?  I dug into this, and it appears to be a harmless bug, which is pretty easy to fix.  The `undefined@undefined` I _think_ is pointing to the fact that you don't have a `name` field in your `package.json`.  That causes the current module to default to `undefined` as the package name. 

Aside from the weird "undefined" stuff - are you seeing anything behaviorally wrong?  If so, can you provide a few repro steps?  Steps I followed:
- Cloned https://github.com/graphql/graphiql
- ran `yarn`
- ran `yarn license-check`
- got this output:

```
yarn license-check        
yarn run v1.22.10
$ jsgl --local ./
Checking package.json...

Checking packages/codemirror-graphql/package.json...

Checking packages/graphiql/package.json...

Checking packages/graphiql-2-rfc-context/package.json...

Checking packages/graphiql-toolkit/package.json...

Checking packages/graphql-language-service/package.json...

Checking packages/graphql-language-service-cli/package.json...

Checking packages/graphql-language-service-interface/package.json...

Checking packages/graphql-language-service-parser/package.json...

Checking packages/graphql-language-service-server/package.json...

valid-url is allowlisted.
Checking packages/graphql-language-service-types/package.json...

Checking packages/graphql-language-service-utils/package.json...

Checking packages/monaco-graphql/package.json...

All green!
✨  Done in 29.30s.
```

**Comment by acao** [comment]
Oh thank you!

There’s a specific PR ill link to tomorrow, but the package json name is likely it!

**Comment by acao** [comment]
https://github.com/graphql/graphiql/pull/1825

this is the PR. I've added the name property to the root package.json and it appears to have fixed it!

the reason you didn't see it on main branch, but the PR shows this error is because we haven't yet changed any root dependencies since adding `jsgl`, only workspace dependencies. so, this project didn't seem to notice it was an issue until it needed to parse the root `package.json`!
